### ISSUE TITLE
Implement different command invocation modes

### ISSUE THREAD

**Issue by s1kx** [s1kx/unison#2]
Commands should be able to be invoked via:

- Channels and private messages
- Messages starting with a mention to the bot
- Messages starting with the command prefix

Which modes should be operational should be configurable.

**Comment by andersfylling** [comment]
- [x] Run commands in both group channels and private messaging
- [x] [Messages starting with a mention to the bot](https://github.com/s1kx/unison/commit/c1e1ab9c55fa96bb6f49108cd6fbb3da3b5bca9a)
- [x] [Messages starting with the command prefix](https://github.com/s1kx/unison/commit/c1e1ab9c55fa96bb6f49108cd6fbb3da3b5bca9a)
- [x] Whether or not a command is invoked by mention and/or a command prefix, should be configurable.

See development and [commandInvokingSettings](https://github.com/s1kx/unison/tree/commandInvokingSettings) branch.

**Comment by andersfylling** [comment]
Command prefixes are still required when writing a PM to the bot
