### ISSUE TITLE
What identifies a message as a potential command?

### ISSUE THREAD

**Issue by andersfylling** [s1kx/unison#4]
Should it be a requirement that every message that should identify as a potential command must do so with a prefix?

**Comment by s1kx** [comment]
Commands should require a prefix only when not used in conjunction with a bot mention.
So, possible modes of command invocation:

- `!help` (Channels/Private)
- `@bot help` (Channels/Private)
- `@bot !help` (Channels/Private)
- `help` (Private)

Other modes, such as `help @bot` seem uncommon and as of now I don't see a reason for incorporating such schemes.
